### ISSUE TITLE
Symlink to pkglist.sh assumes the username to be "pi"

### ISSUE THREAD

**Issue by sidcha** [mainsail-crew/crowsnest#156]
### What happened

The symlink for pkglist.sh in tools/ was broken

### What did you expect to happen

They symlink to be username agnostic.

### How to reproduce

Install mainsail OS on a raspberry-pi using the imager tool and choose a different username for the pi (under the additional settings window).

### Additional information

From a quick look, I think this [line](https://github.com/mainsail-crew/crowsnest/blob/master/tools/libs/core.sh#L46) is at fault. It should derive the path based on $BASE_USER as in other places.

**Comment by mryel00** [comment]
This bug doesn't have to do something with crowsnest directly and is already known. The problem is [this](https://github.com/mainsail-crew/MainsailOS/blob/ba3d5824c6cf05e0c557c40348da75098015f16d/src/modules/postrename/filesystem/root/postrename) module. As the BASE_USER of the MainsailOS image is pi and you rename it with Raspi Imager. The single symlinks and files have to be updated then too. There comes in the postrename script, that currently doesn't work correct and @KwadFan didn't yet have time to fix it.

If you build crowsnest yourself (or use kiauh for example) the symlink is created correctly.
So please open an issue on the [MainsailOS](https://github.com/mainsail-crew/MainsailOS) GitHub.

To fix it atm, just run:
```bash
rm -rf ~/crowsnest/tools/pkglist.sh
ln -sf ~/crowsnest/tools/libs/pkglist-rpi.sh ~/crowsnest/tools/pkglist.sh
```
