### ISSUE TITLE
RPi updates broke camera-streamer

### ISSUE THREAD

**Issue by mnorrsken** [mainsail-crew/crowsnest#157]
### What happened

System updates broke camera-streamer (?). I rebooted my RPi first time in a while and after that my webcam (Logi C270) was not working. However after switching to ustreamer the camera started working. Then I read something about a new version of camera-streamer and got the newest pre-built version and replaced crowsnests version (installed with apt and linked the binary from within crowsnest/bin/camera-streamer), and camera started working again.

### What did you expect to happen

Camera working after update. I guess I expected "camera-streamer" to be updated as part of crowsnest.

### How to reproduce

Update to latest RaspiOS packages without updating camera-streamer and camera stops working. However it don't seem like a lot of people have this problem so maybe it's because of my specific MainsailOS install.

### Additional information

This is just a heads up, feel free to close if it is out of scope for crowsnest.

**Comment by mryel00** [comment]
Hey, we are already aware of this problem. This problem is already mentioned in #143 and comes up every now and then on the [Mainsail Discord](https://discord.gg/mainsail).
The problem is that you compile camera-streamer manually without apt knowing, that it depends on some old libcamera version. So libcamera got an update and broke camera-streamer like that.
Atm you need to recompile camera-streamer manually that everything will work again, or like you did, just isntall the latest pre-compiled version and you won't run into that problem in the future.
